<?php

return [
    'causelist_national' => 'https://hcservices.ecourts.gov.in/ecourtindiaHC/cases/highcourt_causelist.php?state_cd=6&dist_cd=1&court_code=2&stateNm=Assam',
    'causelist_local' => 'https://hcnlservices.in/causelist/view_causelists.php',
    'case_status' => 'https://hcservices.ecourts.gov.in/ecourtindiaHC/index_highcourt.php?state_cd=6&dist_cd=1&court_code=2&stateNm=Assam',
    'neutral_citation' => 'https://hcservices.nagaland.gov.in/neutralcitation.php',
    'display_board' => 'https://board.hcnlservices.in/display/',
    'statistics' => '#',
    'library' => '#',
    'downloads' => '#',
    'justice_clock' => 'https://justiceclock.ecourts.gov.in/justiceClock/?p=home/state&fstate_code=34',
    'ecommittee_newsletters' => 'Newsletters.php',
    'mact_dashboard' => 'https://hcnlservices.in/mact_dashboard/',
    'mact' => 'https://mact.hcnlservices.in/',
    'rti' => '#',
    'escr' => 'https://judgments.ecourts.gov.in/pdfsearch/index.php',
    'court_vc' => '#',
    'e_filing' => '#',
    'epay' => '#',
    'virtual_courts' => '#',
    'njdg' => 'https://njdg.ecourts.gov.in/njdgnew/index.php',
    'ecourts' => 'http://ecourts.gov.in',
    'live_streaming' => 'https://www.youtube.com/@ecourtsnagaland/streams',
    'eservices_portal' => 'https://hcnlservices.in/',
    'whatsapp_channel' => 'https://whatsapp.com/channel/0029Vach5CP42DcbQy9Gsg3o',
];